### PR TITLE
Added parameter to setResourcePath to add posibility to disable warnings thrown

### PR DESCRIPTION
**Pull request by egor-bryzgalov**
Added parameter to `setResourcePath` method to add posibility to disable warnings thrown

Related issue:
[#274](https://github.com/microsoft/build-task-team/issues/274)

### CODE REVIEW

**Review by damccorm — APPROVED** [review]

**Comment by damccorm** [comment]
Can you add the same pr targeting the `releases/3.x` branch?

**Comment by egor-bryzgalov** [comment]
> Can you add the same pr targeting the `releases/3.x` branch? https://github.com/microsoft/azure-pipelines-task-lib/tree/releases/3.x

I [opened it here](https://github.com/microsoft/azure-pipelines-task-lib/pull/670). Could you please take a look. Thank you!

**Comment by damccorm** [comment]
Thanks!

**Comment by damccorm** [comment]
Published!

**Pull request merged**
