### PR TITLE
Update minimatch to version 3.0.5 to fix vulnerability

### PR DESCRIPTION
**Pull request by kirill-ivlev**
Updated package minimatch from 3.0.4 to version 3.0.5.

Related issue: https://github.com/microsoft/azure-pipelines-task-lib/issues/832

### CODE REVIEW

**Review by KonstantinTyukalov — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Comment by kirill-ivlev** [comment]
@mmrazik Could you please review this PR

**Comment by anatolybolshakov** [comment]
@kirill-ivlev please bump package version for further release as well

**Comment by anatolybolshakov** [comment]
This should help to fix https://github.com/microsoft/google-play-vsts-extension/issues/342 also (minimatch vulnerability).

**Comment by alexander-smolyakov** [comment]
@mmrazik could you please take a look at this PR?

**Review by mmrazik — APPROVED** [review]

**Pull request merged**
