### PR TITLE
Resolve vulnerabilities in dependencies

### PR DESCRIPTION
**Pull request by AndreyIvanov42**
- Bumped shelljs to 0.8.5
- adm-zip to 0.5.9
- fixed tests (due to changes in methods shelljs)

Tested only with mocha tests

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
@AndreyIvanov42 where are ensureStarted and ensureTool methods affected - could you please double-check that you've tested scenarios in which these methods are being used?

**Comment by AndreyIvanov42** [comment]
@anatolybolshakov 
I double-checked `ensureStarted` and `ensureTool` methods. They are used only in tests. 
But since many methods of this library are wrappers over shelljs methods, I need to make sure that backward compatibility is not broken.

**Comment by anatolybolshakov** [comment]
Please bump package/package-lock versions

**Review by anatolybolshakov — APPROVED** [review]

**Review by max-zaytsev — APPROVED** [review]

**Comment by kriti218** [comment]
@AndreyIvanov42 When are we going to have 3.2.0 as the latest version to download? It looks like shelljs vulnerability was fixed in this PR #815 when version was updated to 0.8.5 from 8.4.

**Comment by AndreyIvanov42** [comment]
@kriti218 
New version is available

**Pull request merged**
