### PR TITLE
Make exec and execSync functions take Partial<IExec(Sync)Options>

### PR DESCRIPTION
**Pull request by ILMTitan**

### CODE REVIEW

**Comment by damccorm** [comment]
I believe Partial is only available in TypeScript 2, this project uses Typescript 1, so I don't think this update will work. I'm going to close here - feel free to reopen if appropriate.

**Comment by bryanmacfarlane** [comment]
We should update to TypeScript 2

**Comment by damccorm** [comment]
@ILMTitan we are now using TypeScript 3 - are you still interested in reviving this? What's your use case where you needed it?

**Comment by ILMTitan** [comment]
I am no longer working on the project that prompted this.

**Pull request closed without merging**
