### PR TITLE
add satisfies property to task.schema.json

### PR DESCRIPTION
**Pull request by teh13th**

### CODE REVIEW

**Comment by teh13th** [comment]
Can anyone review this?

**Comment by teh13th** [comment]
@KonstantinTyukalov maybe yo can help with this?

**Review by KonstantinTyukalov — APPROVED** [review]
Hey @teh13th! Thanks for your contribution!
LGTM, please check my suggestion

**Review by vmapetr — APPROVED** [review]

**Comment by teh13th** [comment]
@KonstantinTyukalov, @vmapetr this check don't want to go:
image

**Comment by teh13th** [comment]
> /azp run

@KonstantinTyukalov it didn't help :(

**Pull request closed without merging**
